### ISSUE TITLE
test

### ISSUE THREAD

**Issue by prensmiskin** [prensmiskin/vollley-one#1]
I want to show the latest post in the top row. How can I do this on android. I am using mysql- php as webservis.

  I'm trying to make twitter clonu. last post, needs to be seen in the top row.

Github Project

https://github.com/prensmiskin/vollley-one/tree/master/volleydenemetwo/app/src/main/java/com/example/volleydenemetwo

```
public void kisiekle(){
        String url = "https://goldgym.pro/akis.php";
        final String akiss = akis.getText().toString().trim();


        StringRequest istek = new StringRequest(Request.Method.POST, url, new Response.Listener<String>() {
            @Override
            public void onResponse(String response) {
                Log.e("Cevap",response);

                try{
                    JSONObject jsonObject = new JSONObject(response);
                    JSONArray movies = jsonObject.getJSONArray("employees");




                    StringBuilder sb = new StringBuilder();

                  for (int i=0; i < movies.length();i++){
                        JSONObject b = movies.getJSONObject(i);

                       String akis_ad = b.getString("akis");


                      akisone.append(akis_ad + ","  + "\n\n");





                    }
```
web Service / mysql - php
twit https://github.com/prensmiskin/vollley-one/blob/master/akis.php
login https://github.com/prensmiskin/vollley-one/blob/master/login.php register
https://github.com/prensmiskin/vollley-one/blob/master/myphp.php

screenshot https://user-images.githubusercontent.com/40228440/66035919-bb89fd00-e514-11e9-8151-ebba56fc7670.png

**Comment by prensmiskin** [comment]
![Screenshot_1570877032](https://user-images.githubusercontent.com/40228440/66700357-06b3c500-ecf8-11e9-97fd-8de4a7799e1a.png)

**Comment by prensmiskin** [comment]
```
2019-10-16 14:42:42.011 8322-8322/? I/cyclerviewloca: Not late-enabling -Xcheck:jni (already on)
2019-10-16 14:42:42.044 8322-8322/? E/cyclerviewloca: Unknown bits set in runtime_flags: 0x8000
2019-10-16 14:42:42.044 8322-8322/? W/cyclerviewloca: Unexpected CPU variant for X86 using defaults: x86
2019-10-16 14:42:42.396 8322-8322/com.example.recyclerviewlocal W/RenderThread: type=1400 audit(0.0:32): avc: denied { write } for name="property_service" dev="tmpfs" ino=6829 scontext=u:r:untrusted_app:s0:c142,c256,c512,c768 tcontext=u:object_r:property_socket:s0 tclass=sock_file permissive=0
2019-10-16 14:42:42.401 8322-8357/com.example.recyclerviewlocal D/libEGL: Emulator has host GPU support, qemu.gles is set to 1.
2019-10-16 14:42:42.411 8322-8357/com.example.recyclerviewlocal W/libc: Unable to set property "qemu.gles" to "1": connection failed; errno=13 (Permission denied)
2019-10-16 14:42:42.467 8322-8357/com.example.recyclerviewlocal D/libEGL: loaded /vendor/lib/egl/libEGL_emulation.so
2019-10-16 14:42:42.468 8322-8357/com.example.recyclerviewlocal D/libEGL: loaded /vendor/lib/egl/libGLESv1_CM_emulation.so
2019-10-16 14:42:42.483 8322-8357/com.example.recyclerviewlocal D/libEGL: loaded /vendor/lib/egl/libGLESv2_emulation.so
2019-10-16 14:42:42.635 8322-8322/com.example.recyclerviewlocal W/cyclerviewloca: Accessing hidden method Landroid/view/View;->computeFitSystemWindows(Landroid/graphics/Rect;Landroid/graphics/Rect;)Z (greylist, reflection, allowed)
2019-10-16 14:42:42.635 8322-8322/com.example.recyclerviewlocal W/cyclerviewloca: Accessing hidden method Landroid/view/ViewGroup;->makeOptionalFitsSystemWindows()V (greylist, reflection, allowed)
2019-10-16 14:42:42.764 8322-8351/com.example.recyclerviewlocal D/HostConnection: HostConnection::get() New Host Connection established 0xd624c2d0, tid 8351
2019-10-16 14:42:42.781 8322-8351/com.example.recyclerviewlocal D/HostConnection: HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_dma_v1 ANDROID_EMU_direct_mem ANDROID_EMU_host_composition_v1 ANDROID_EMU_host_composition_v2 ANDROID_EMU_YUV420_888_to_NV21 ANDROID_EMU_YUV_Cache GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_gles_max_version_2 
2019-10-16 14:42:42.783 8322-8322/com.example.recyclerviewlocal D/AndroidRuntime: Shutting down VM
2019-10-16 14:42:42.785 8322-8351/com.example.recyclerviewlocal W/OpenGLRenderer: Failed to choose config with EGL_SWAP_BEHAVIOR_PRESERVED, retrying without...
2019-10-16 14:42:42.786 8322-8322/com.example.recyclerviewlocal E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.recyclerviewlocal, PID: 8322
    java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at java.util.ArrayList.get(ArrayList.java:437)
        at com.example.recyclerviewlocal.MyAdapter.onBindViewHolder(MyAdapter.java:39)
        at com.example.recyclerviewlocal.MyAdapter.onBindViewHolder(MyAdapter.java:15)
        at androidx.recyclerview.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:6781)
        at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6823)
        at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5752)
        at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6019)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5858)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5854)
        at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2230)
        at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1557)
        at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1517)
        at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:612)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3924)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:3641)
        at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4194)
        at android.view.View.layout(View.java:21912)
        at android.view.ViewGroup.layout(ViewGroup.java:6260)
        at androidx.constraintlayout.widget.ConstraintLayout.onLayout(ConstraintLayout.java:1915)
        at android.view.View.layout(View.java:21912)
        at android.view.ViewGroup.layout(ViewGroup.java:6260)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
        at android.view.View.layout(View.java:21912)
        at android.view.ViewGroup.layout(ViewGroup.java:6260)
        at androidx.appcompat.widget.ActionBarOverlayLayout.onLayout(ActionBarOverlayLayout.java:446)
        at android.view.View.layout(View.java:21912)
        at android.view.ViewGroup.layout(ViewGroup.java:6260)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
        at android.view.View.layout(View.java:21912)
        at android.view.ViewGroup.layout(ViewGroup.java:6260)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
        at android.view.View.layout(View.java:21912)
        at android.view.ViewGroup.layout(ViewGroup.java:6260)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
        at com.android.internal.policy.DecorView.onLayout(DecorView.java:779)
        at android.view.View.layout(View.java:21912)
        at android.view.ViewGroup.layout(ViewGroup.java:6260)
        at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3080)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2590)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1721)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7598)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:966)
        at android.view.Choreographer.doCallbacks(Choreographer.java:790)
        at android.view.Choreographer.doFrame(Choreographer.java:725)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:951)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
2019-10-16 14:42:42.786 8322-8322/com.example.recyclerviewlocal E/AndroidRuntime:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
2019-10-16 14:42:42.790 8322-8351/com.example.recyclerviewlocal D/eglCodecCommon: setVertexArrayObject: set vao to 0 (0) 0 0
2019-10-16 14:42:42.790 8322-8351/com.example.recyclerviewlocal D/EGL_emulation: eglCreateContext: 0xd621a360: maj 2 min 0 rcv 2
2019-10-16 14:42:42.810 8322-8351/com.example.recyclerviewlocal D/EGL_emulation: eglMakeCurrent: 0xd621a360: ver 2 0 (tinfo 0xd620f1d0)
2019-10-16 14:42:42.820 8322-8322/com.example.recyclerviewlocal I/Process: Sending signal. PID: 8322 SIG: 9

```

**Comment by prensmiskin** [comment]
![8636ba26-053a-4189-8f99-9df68ce57007](https://user-images.githubusercontent.com/40228440/68531586-f4dc3680-0324-11ea-815a-805326e70f04.JPG)

**Comment by prensmiskin** [comment]
[Graphic Design.pdf](https://github.com/prensmiskin/vollley-one/files/3827698/Graphic.Design.pdf)

**Comment by prensmiskin** [comment]
![Screenshot from 2019-11-12 15-23-48](https://user-images.githubusercontent.com/40228440/68671603-bcc13780-0560-11ea-8a05-bb916fccd41c.png)

**Comment by prensmiskin** [comment]
![IMG_6321](https://user-images.githubusercontent.com/40228440/68990674-f2b73200-0866-11ea-8996-5cb86b03443a.JPG)

![IMG_6440](https://user-images.githubusercontent.com/40228440/68990676-f34fc880-0866-11ea-9f6f-d036c98d4006.JPG)
![IMG_6446](https://user-images.githubusercontent.com/40228440/68990677-f34fc880-0866-11ea-92e7-ddb26e7f5e15.JPG)
![IMG_6460](https://user-images.githubusercontent.com/40228440/68990662-c8fe0b00-0866-11ea-8ddd-252bdaf53773.JPG)
![IMG_6469](https://user-images.githubusercontent.com/40228440/68990653-b71c6800-0866-11ea-8f1b-4f081f041abe.JPG)
![IMG_9498](https://user-images.githubusercontent.com/40228440/68990654-b71c6800-0866-11ea-8bc5-5fcf226e9e65.JPG)
![IMG_9604](https://user-images.githubusercontent.com/40228440/68990655-b71c6800-0866-11ea-9a73-56fe56005c73.JPG)
![IMG_9648](https://user-images.githubusercontent.com/40228440/68990656-b7b4fe80-0866-11ea-8791-36cee0da3799.JPG)
![IMG_9706](https://user-images.githubusercontent.com/40228440/68990657-b84d9500-0866-11ea-9570-91369ca07cda.JPG)

**Comment by prensmiskin** [comment]
![IMG_9498](https://user-images.githubusercontent.com/40228440/68991537-dcae6f00-0870-11ea-8c3b-63557869218f.JPG)

**Comment by prensmiskin** [comment]
![Alphabet](https://user-images.githubusercontent.com/40228440/68992004-48470b00-0876-11ea-8c26-4cae2b8bec71.jpg)

**Comment by prensmiskin** [comment]
![Screenshot from 2019-12-31 13-04-52](https://user-images.githubusercontent.com/40228440/71620153-5c05c100-2bd9-11ea-80f6-6ff387b238e5.png)

**Comment by prensmiskin** [comment]
![Screenshot from 2019-12-31 14-25-40](https://user-images.githubusercontent.com/40228440/71620173-7b045300-2bd9-11ea-9e3a-faff67703186.png)

**Comment by prensmiskin** [comment]
![DSC00148](https://user-images.githubusercontent.com/40228440/71621045-36c78180-2bde-11ea-96c0-dbbe2b8641e8.JPG)

**Comment by prensmiskin** [comment]
![Screenshot_1578749633](https://user-images.githubusercontent.com/40228440/72205207-6f464580-3491-11ea-92a5-7c9fbd51d3c3.png)
![stackoverflow com_questions_59694883_my-location-button-is-not-shown-in-the-navigation-drawer(iPhone 6_7_8)](https://user-images.githubusercontent.com/40228440/72205211-766d5380-3491-11ea-9ded-0dd8d31f7b43.png)

**Comment by prensmiskin** [comment]
![Screenshot from 2020-01-11 16-53-28](https://user-images.githubusercontent.com/40228440/72205359-0c55ae00-3493-11ea-9c25-e1a6876aa2ef.png)

**Comment by prensmiskin** [comment]
![Screenshot_1579168094](https://user-images.githubusercontent.com/40228440/72513860-b734e600-385e-11ea-8e66-ebacc25508f8.png)
![Screenshot_1579168091](https://user-images.githubusercontent.com/40228440/72513871-ba2fd680-385e-11ea-925a-2dd9cc050654.png)

**Comment by prensmiskin** [comment]
![Screenshot from 2020-03-19 14-36-15](https://user-images.githubusercontent.com/40228440/77063940-91a79280-69ef-11ea-96db-2883a0c5d05a.png)

**Comment by prensmiskin** [comment]
![dfdsfds](https://user-images.githubusercontent.com/40228440/77088947-376df800-6a16-11ea-8b54-405c1ffbae2a.PNG)

**Comment by prensmiskin** [comment]
![grafikerler](https://user-images.githubusercontent.com/40228440/77148789-4b127080-6aa1-11ea-9a25-6394efef2466.PNG)

**Comment by prensmiskin** [comment]
![WhatsApp Image 2020-03-20 at 10 50 12 AM](https://user-images.githubusercontent.com/40228440/77149664-29b28400-6aa3-11ea-9215-d13a860567ae.jpeg)
![WhatsApp Image 2020-03-20 at 10 45 19 AM](https://user-images.githubusercontent.com/40228440/77149669-2d460b00-6aa3-11ea-9017-8897a427b77d.jpeg)

**Comment by prensmiskin** [comment]
![Screenshot from 2020-03-24 14-34-05](https://user-images.githubusercontent.com/40228440/77424342-fdb83b00-6de1-11ea-899f-5957fe23ea6b.png)

**Comment by prensmiskin** [comment]
![Screenshot from 2020-03-24 15-26-34](https://user-images.githubusercontent.com/40228440/77425505-e24e2f80-6de3-11ea-9715-442a52812959.png)

**Comment by prensmiskin** [comment]
![Screenshot from 2020-03-24 15-50-21](https://user-images.githubusercontent.com/40228440/77427340-43c3cd80-6de7-11ea-9abe-1f551632491c.png)

**Comment by prensmiskin** [comment]
![Screenshot from 2020-03-24 16-00-26](https://user-images.githubusercontent.com/40228440/77428102-9c479a80-6de8-11ea-847d-b5955f987c19.png)

**Comment by prensmiskin** [comment]
![IMG_20200324_161315](https://user-images.githubusercontent.com/40228440/77428879-d9605c80-6de9-11ea-907e-f1cd2f582ba9.jpg)
![IMG_20200324_161007](https://user-images.githubusercontent.com/40228440/77428887-db2a2000-6de9-11ea-9518-e5717ab9aee5.jpg)

**Comment by prensmiskin** [comment]
[Urban.pdf](https://github.com/prensmiskin/vollley-one/files/4381301/Urban.pdf)

**Comment by prensmiskin** [comment]
[furkankuru.pdf](https://github.com/prensmiskin/vollley-one/files/4399095/furkankuru.pdf)

**Comment by prensmiskin** [comment]
![WhatsApp Image 2020-03-03 at 9 54 51 PM](https://user-images.githubusercontent.com/40228440/78042133-4b045180-737a-11ea-9cb1-256a8173ab1d.jpeg)

**Comment by prensmiskin** [comment]
![coderhq_90056019_205012877494723_5492334459703787501_n](https://user-images.githubusercontent.com/40228440/78460889-77e39c00-76cd-11ea-9121-a4afbd50a68b.jpg)

**Comment by prensmiskin** [comment]
![coderhq_75562961_1174418119413630_8581642300053247242_n](https://user-images.githubusercontent.com/40228440/78461780-9ac57e80-76d4-11ea-9a6c-da641199542b.jpg)

**Comment by prensmiskin** [comment]
![Street](https://user-images.githubusercontent.com/40228440/78979280-323b2f00-7b24-11ea-9d98-5d654748fc0f.jpg)

**Comment by prensmiskin** [comment]
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/40228440/80598239-b7ce4280-8a31-11ea-8ed9-7810fd8d1a12.gif)

**Comment by prensmiskin** [comment]
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/40228440/80598559-3b882f00-8a32-11ea-8de6-4040d049e6bb.gif)

**Comment by prensmiskin** [comment]
![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/40228440/80598643-565aa380-8a32-11ea-84b7-e72768b95168.gif)

**Comment by prensmiskin** [comment]
[resume-oguzhan-gumus-android-developer-ubuntu.pdf](https://github.com/prensmiskin/vollley-one/files/4598542/resume-oguzhan-gumus-android-developer-ubuntu.pdf)

**Comment by prensmiskin** [comment]
![header-bg](https://user-images.githubusercontent.com/40228440/84194300-7ce61280-aaa5-11ea-8a70-53190db165e8.jpg)

**Comment by prensmiskin** [comment]
![sıkıs](https://user-images.githubusercontent.com/40228440/84194766-30e79d80-aaa6-11ea-89a9-d9f71e51e666.jpg)

**Comment by prensmiskin** [comment]
![header-bg-min](https://user-images.githubusercontent.com/40228440/84195115-b53a2080-aaa6-11ea-8272-5d1d8ba68297.jpg)

**Comment by prensmiskin** [comment]
![hairdresser-showing-sample-hair-color_23-2147769739-min (2)](https://user-images.githubusercontent.com/40228440/84265770-04766480-ab2c-11ea-9f00-6394d6c829d4.jpg)

**Comment by prensmiskin** [comment]
![crop-stylist-using-hairdryer-brush_23-2147769848-min (1)](https://user-images.githubusercontent.com/40228440/84267168-4f917700-ab2e-11ea-9e1e-407a67356a59.jpg)

**Comment by prensmiskin** [comment]
![ggg-min](https://user-images.githubusercontent.com/40228440/85135961-9b879e80-b247-11ea-9bcd-718e566cefde.jpg)

**Comment by prensmiskin** [comment]
[beyonsplustwo.pdf](https://github.com/prensmiskin/vollley-one/files/4809402/beyonsplustwo.pdf)

**Comment by prensmiskin** [comment]
![WhatsApp Image 2021-03-05 at 08 39 18 (1)](https://user-images.githubusercontent.com/40228440/110206049-a09b8500-7e8c-11eb-9322-a60ecfccc222.jpeg)
![WhatsApp Image 2021-03-05 at 08 39 18](https://user-images.githubusercontent.com/40228440/110206055-a729fc80-7e8c-11eb-9846-2f8fa3773ef7.jpeg)
![WhatsApp Image 2021-03-05 at 08 39 17 (1)](https://user-images.githubusercontent.com/40228440/110206058-a85b2980-7e8c-11eb-93a4-c5c09cc90beb.jpeg)
![WhatsApp Image 2021-03-05 at 08 39 17](https://user-images.githubusercontent.com/40228440/110206059-a98c5680-7e8c-11eb-9fcd-9cb281b39643.jpeg)

**Comment by prensmiskin** [comment]
![androidone](https://user-images.githubusercontent.com/40228440/116783243-60c0da80-aa96-11eb-9fbe-fbc2428fee3c.jpg)

**Comment by prensmiskin** [comment]
![a](https://user-images.githubusercontent.com/40228440/117187329-7ad72180-ade4-11eb-91b6-5b05b4c15b89.png)
